### ISSUE TITLE
Question about poses_bounds.npy in the ExBluRF dataset

### ISSUE THREAD

**Issue by hmyang0727** [taekkii/ExBluRF#1]
Thanks for your great work!

There are poses_bounds.npy and poses_bounds_subframes.npy in each scene of your dataset.

Are they estimated from blurry training views + sharp test views or sharp (ground-truth) training views + sharp test views?

The reason that I am asking is that when I tried to estimate camera poses from blurry training views using COLMAP, COLMAP failed to estimate camera poses.

I suspect the reason is that training views contain severe blur so that COLMAP cannot estimate feature points.

Therefore, I want to figure out whether estimating camera poses from blurry images from ExBluRF dataset is possible or not.

Thank you in advance.

**Comment by taekkii** [comment]
Hi, thanks for the attention toward our work.

The camera extrinsic in poses_bounds.npy is estimated from SHARP training views + sharp GT views, for the very reason you have pointed out: it is challenging to extract feature points from extreme blurry observations and obtained points are also erroneous. 

ExBluRF does not assume noisy initial pose caused by blur (which we have to admit, is an experimental/non-practical settings.) We have been aware of that problem and accomplished new work, DeblurGS, to address the noisy-pose problem:
[link](https://github.com/taekkii/deblurgs). Although the readme and code of DeblurGS is still being cleaned up, visiting is always welcome. 

DeblurGS also suffers COLMAP failure for ExBlur Dataset when we try to run COLMAP with **blurry observations only**. Therefore, in DeblurGS,
1) we loosen the constraint for COLMAP hyperparameters (e.g. the threshold for deciding "match" between feature points,) and
2) we only utilized 70% of blurry views with which the COLMAP successes.

So, to answer your question about if estimating the poses for blurry images are possible or not, it is possible if you admit very high error with loosen COLMAP constraints.

Thank you.

**Comment by hmyang0727** [comment]
I appreciate your kind response! 

All my questions have been clarified :)
