### ISSUE TITLE
numeric results not same in DeblurNeRF and BADNeRF

### ISSUE THREAD

**Issue by HuTaoMylove** [taekkii/ExBluRF#4]
Thanks for your great work! I really confuse about the numeric results in your paper.In the three paper,the result conflicts and very weird.In badnerf,their method's performence is much better than deblurnerf.However,In your paper deblurnerf is better than badnerf.What's more,your method still base on badnerf and get sota?It's so wired ,I want to get your suggestions.

**Comment by taekkii** [comment]
Hi, please allow me to explain.

First of all, we want to emphasize that our method is **not based** on bad-nerf. It was a concurrent work. It is true that BAD-NeRF was published earlier than ours (CVPR2023 vs. ICCV) but at the time when we submitted the first draft, the code for BAD-NeRF was not published. The table was updated later at camera-ready phase.

About the performance gap between Deblur-NeRF and BAD-NeRF, I assume it is the performance on the synthetic dataset (Cozy2room Factory Pool Tanabata Trolley) because BAD-NeRF does not report the metric regarding real dataset. Actually, the synthetic dataset used in BAD-NeRF is different to ours. As written in our paper, we re-syntheisze 5 Blender scenes to be more challenging, and Deblur-NeRF ourperforms BAD-NeRF in the challenging scenario. I want to highlight that we indeed used the official BAD-NeRF repo. 

Also, it is noteworthy that we are not the only work which have reported deblur-nerf getting superior result than BAD-NeRF in majority of settings (c.f. SMURF (https://arxiv.org/pdf/2403.07547) also reported that deblur-nerf doing better than BAD-NeRF). I'm cautious to guess the reason for the performance gap because we are not the authors of BAD-NeRF. The code of BAD-NeRF is available, so you may want to experiment yourself. 

Thank you.

**Comment by HuTaoMylove** [comment]
I'm sorry for misunderstanding your work,thank you for your reply and your nice work!
